require(foreign)
require(ggplot2)
require(MASS)
require(Hmisc)
require(reshape2)
require(plyr)
library(nnet)
library(dplyr)
library(ggplot2)
library(plotly)
library(grid)
library(gridExtra)
library(DT)
library(GGally)
library(randomForest)
levels(x$loan)
LOAN<-factor(x$loan)
levels(LOAN)
levels(LOAN)[1]<-"0"
levels(LOAN)[2]<-"-1"
levels(LOAN)[3]<-"1"
levels(x$marital)
MARITAL<-factor(x$marital)
levels(MARITAL)
levels(MARITAL)[1]<-"0"
levels(MARITAL)[2]<-"2"
levels(MARITAL)[3]<-"1"
levels(MARITAL)[4]<-"-1"
head(MARITAL)
levels(x$default)
DEFAULT<-factor(x$default)
levels(DEFAULT)[1]<-"0"
levels(DEFAULT)[2]<-"-1"
levels(DEFAULT)[3]<-"1"
head(DEFAULT)
levels(x$housing)
HOUSING<-factor(x$housing)
levels(HOUSING)[1]<-"0"
levels(HOUSING)[2]<-"-1"
levels(HOUSING)[3]<-"1"
head(HOUSING)
levels(x$education)
EDUCATION<-factor(x$education)
levels(EDUCATION)[1]<-"1"
levels(EDUCATION)[2]<-"2"
levels(EDUCATION)[3]<-"3"
levels(EDUCATION)[4]<-"4"
levels(EDUCATION)[5]<-"0"
levels(EDUCATION)[6]<-"6"
levels(EDUCATION)[7]<-"5"
levels(EDUCATION)[8]<-"-1"
head(EDUCATION)
levels(x$job)
JOB<-factor(x$job)
levels(JOB)[9]<-"1"
levels(JOB)[10]<-"2"
levels(JOB)[11]<-"0"
levels(JOB)[12]<-"-1"
levels(JOB)[5]<-"3"
levels(JOB)[6]<-"4"
levels(JOB)[7]<-"5"
levels(JOB)[8]<-"6"
levels(JOB)[1]<-"7"
levels(JOB)[2]<-"8"
levels(JOB)[3]<-"9"
levels(JOB)[4]<-"10"
head(JOB)