require(foreign)
require(ggplot2)
require(MASS)
require(Hmisc)
require(reshape2)
require(plyr)
library(nnet)
library(dplyr)
library(ggplot2)
library(plotly)
library(grid)
library(gridExtra)
library(DT)
library(GGally)
library(randomForest)
fit2<-multinom(DEFAULT~x$age+JOB+EDUCATION+MARITAL)
summary(fit2)
head(fitted(fit2))
x2 = data.frame(DEFAULT,x$age,JOB,EDUCATION,MARITAL)
fit2<-polr(x$default ~ x$age + x$job + x$education + x$marital ,data = x, Hess=TRUE)
summary(fit2)
head(fitted(fit2))
ctable2 <- coef(summary(fit2))
p2 <- pnorm(abs(ctable2[, "t value"]), lower.tail = FALSE)*2
ci2 <- confint(fit2)
exp(coef(fit2))
exp(cbind(OR = coef(fit2), ci2))
summary(fit2)
summary(update(fit2, method = "probit", Hess = TRUE) , digits = 4)
summary(update(fit2, method = "logistic", Hess = TRUE) , digits = 4)
summary(update(fit2, method = "cloglog", Hess = TRUE) , digits = 4)
head(predict(fit2, x2, type = "p"))
addterm(fit2, ~.^2, test = "Chisq")
fit22 <- stepAIC(fit2, ~.^2)
fit22
summary(fit22)
fit22$anova
anova(fit2, fit22)
fit222 <- update(fit2, Hess = TRUE)
pr2 = profile(fit222)
confint(pr2)
plot(pr2)
pairs(pr2)