require(foreign)
require(ggplot2)
require(MASS)
require(Hmisc)
require(reshape2)
require(plyr)
library(nnet)
library(dplyr)
library(ggplot2)
library(plotly)
library(grid)
library(gridExtra)
library(DT)
library(GGally)
library(randomForest)
fit3<-multinom(HOUSING~x$age+JOB+EDUCATION+MARITAL)
summary(fit3)
head(fitted(fit3))
names(x)
x3 = data.frame(HOUSING,x$age,JOB,EDUCATION,MARITAL)
fit3<-polr(x$housing ~ x$age + x$job + x$education + x$marital ,data = x, Hess=TRUE)
summary(fit3)
head(fitted(fit3))
ctable3 <- coef(summary(fit3))
p3 <- pnorm(abs(ctable3[, "t value"]), lower.tail = FALSE)*2
ci3 <- confint(fit3)
exp(coef(fit3))
exp(cbind(OR = coef(fit3), ci3))
summary(fit3)
summary(update(fit3, method = "probit", Hess = TRUE) , digits = 4)
summary(update(fit3, method = "logistic", Hess = TRUE) , digits = 4)
summary(update(fit3, method = "cloglog", Hess = TRUE) , digits = 4)
head(predict(fit3, x3, type = "p"))
addterm(fit3, ~.^2, test = "Chisq")
fit33 <- stepAIC(fit3, ~.^2)
fit33
summary(fit33)
fit33$anova
anova(fit3, fit33)
fit333 <- update(fit3, Hess = TRUE)
pr3 = profile(fit333)
confint(pr3)
plot(pr3)
pairs(pr3)